### ISSUE TITLE
terraform - Azure add tags to existing resources 

### ISSUE THREAD

**Issue by cibisrinivasan** [claranet/terraform-azurerm-tagging#1]
Can you please guide me what exact resource and provider to be used in terraform for all resources in azure(vms, storage, RG etc..)
I have done with Azure cli and powershell commands, but need help on terraform.

**Comment by BzSpi** [comment]
Hello @cibisrinivasan 

You can find a comprehensive example here https://github.com/claranet/terraform-azurerm-tagging/tree/master/examples/main.

The implementation rely on CLI an can be used on all resources types. Please note this module is intended to be used as a workaround for some specific cases. The best way to have tagging one Azure resources is to use the Terraform resources directly.
