### ISSUE TITLE
Submodule does not support PowerShell (for Windows build runners)

### ISSUE THREAD

**Issue by epopisces** [claranet/terraform-azurerm-tagging#2]
I would like to contribute to the repository to allow use of the tagging submodule on Windows platforms (local-exec provisioner using a PowerShell interpreter) in a way that does not impact existing use for bash implementations.  Something like so:

### variables.tf
```terraform
# defaults to "bash" to maintain default operation

variable "interpreter" {
  description = "Indicates which shell the script should run in"
  type        = string
  default     = "bash"
  validation {
    condition     = contains(["bash", "PowerShell"], var.interpreter)
    error_message = "The value for interpreter must be either `bash` or `PowerShell`."
  }
}
```

### tagging.tf
```terraform
...
  provisioner "local-exec" {
    interpreter = var.interpreter == "PowerShell" ? ["PowerShell"] : ["/bin/bash", "-c"]
    command     = var.interpreter == "PowerShell" ? templatefile("${path.module}/script/tag.ps1.tmpl",
      {
        behavior        = var.behavior
        resource_id     = var.resource_ids[count.index]
        tags            = local.tags
        subscription_id = data.azurerm_client_config.current.subscription_id
      }
    ) : templatefile("${path.module}/script/tag.sh.tmpl",
      {
        behavior        = var.behavior
        resource_id     = var.resource_ids[count.index]
        tags            = local.tags
        subscription_id = data.azurerm_client_config.current.subscription_id
      }
    )
  }
...
```

tag.ps1.tmpl would then be a modified copy of the tag.sh.tmpl file with PowerShell syntax.

If that is not desirable based on the vision/intended audience of the module I'd be willing to maintain a fork of the repository.  This module perfectly solves a need I have in my organization for nondestructively merging Azure resource tags, but we have Windows runners in some environments.

**Comment by epopisces** [comment]
Debated using something like this:
https://stackoverflow.com/questions/52628749/set-terraform-default-interpreter-for-local-exec

```terraform
locals {
  # Directories start with "C:..." on Windows; All other OSs use "/" for root.
  is_windows = substr(pathexpand("~"), 0, 1) == "/" ? false : true
}
```

But the module shouldn't assume interpreter based on OS--it is better to allow the calling project to specify the var instead if needed (since PowerShell can be and often is installed on Linux as well, particularly for Azure DevOps agent runners).  The calling project could always use the above mechanism and pass the result to the module in any case.

**Comment by BzSpi** [comment]
Hello @epopisces 

Thanks for your feedback. This is an interesting improvement, feel free to open a pull request to have this implemented.
Also, the OS detection seems a good idea.

**Comment by epopisces** [comment]
@BzSpi pull request opened!
